### ISSUE TITLE
MacOs Monterey

### ISSUE THREAD

**Issue by mrbouny** [zqzten/alfred-web-search-suggest#29]
Hi Zach, the alfred search workflow doesn't work anymore with the macos Monterey upgrade.
Would be wonderful to have an update ❤️ Thanks in advance

**Comment by zqzten** [comment]
Thanks for the feedback. Apple has removed the system PHP since macOS Monterey (12.0), so you should install PHP manually to continue using this workflow. Please check [this note](https://github.com/zqzten/alfred-web-search-suggest#important-note-for-macos-monterey-120-and-above) in the updated README for instructions. Sorry for the inconvenience!
